#!/usr/bin/env python3

from bs4 import BeautifulSoup

import sys

def main():
    infile = sys.argv[1]
    with open(infile) as f:
        soup = BeautifulSoup(f, features="html.parser")
        h1s = soup.find_all("h1", class_="devsite-page-title")
        bodies = soup.find_all("div", class_="devsite-article-body")
        if len(h1s) != 1:
            eprint(f'No h1 for {infile}')
        if len(bodies) != 1:
            eprint(f'No bodies for {infile}')
        print(h1s[0], bodies[0])

def eprint(*args, **kwargs):
    print(u"\u001b[31m", *args, u"\u001b[0m", file=sys.stderr, **kwargs)
    sys.exit(0)

if __name__ == '__main__':
    main()
